import { jsPDF } from 'jspdf';
import { getChat } from '@/services/healthService';

export interface DownloadChatReportOptions {
  token: string;
  chatId: number;
}

type RGB = [number, number, number];

const BLUE: RGB = [31, 134, 255];
const VIOLET: RGB = [139, 108, 255];
const CYAN: RGB = [62, 232, 255];
const MINT: RGB = [108, 242, 193];

const BRAND_50: RGB = [238, 246, 255];
const BRAND_900: RGB = [10, 21, 48];

const TEXT_2: RGB = [184, 196, 217];
const TEXT_3: RGB = [122, 138, 166];
const TEXT_BODY: RGB = [40, 50, 75];
const TEXT_MID: RGB = [90, 105, 130];

const ANSWER_BG: RGB = [230, 252, 244];
const ANSWER_FG: RGB = [14, 80, 52];
const SKIP_BG: RGB = [255, 238, 244];
const SKIP_FG: RGB = [155, 40, 65];

const DIVIDER: RGB = [218, 225, 240];
const NAVY: RGB = [8, 11, 18];

const FOOTER_H = 20;
const HEADER_H = 30;
const MARGIN = 18;

function drawGradientLine(
  doc: jsPDF,
  x: number,
  y: number,
  w: number,
  h: number,
) {
  const steps = 40;
  const stepW = w / steps;
  const stops: RGB[] = [BLUE, VIOLET, CYAN];

  for (let i = 0; i < steps; i++) {
    const t = i / (steps - 1);

    let r: number;
    let g: number;
    let b: number;

    if (t <= 0.5) {
      const u = t * 2;
      r = Math.round(stops[0][0] + (stops[1][0] - stops[0][0]) * u);
      g = Math.round(stops[0][1] + (stops[1][1] - stops[0][1]) * u);
      b = Math.round(stops[0][2] + (stops[1][2] - stops[0][2]) * u);
    } else {
      const u = (t - 0.5) * 2;
      r = Math.round(stops[1][0] + (stops[2][0] - stops[1][0]) * u);
      g = Math.round(stops[1][1] + (stops[2][1] - stops[1][1]) * u);
      b = Math.round(stops[1][2] + (stops[2][2] - stops[1][2]) * u);
    }

    doc.setFillColor(r, g, b);
    doc.rect(x + i * stepW, y, stepW + 0.2, h, 'F');
  }
}

function drawPageHeader(doc: jsPDF, pageW: number) {
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, pageW, HEADER_H, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);

  const aiText = 'AI ';
  const helpDeskText = 'HelpDesk';

const totalW = doc.getTextWidth(aiText + helpDeskText);
const startX = pageW / 2 - totalW / 2;
const centerY = HEADER_H / 2 + 1.5;

  doc.setTextColor(...BLUE);
  doc.text(aiText, startX, centerY);

  const aiW = doc.getTextWidth(aiText);

  doc.setTextColor(255, 255, 255);
  doc.text(helpDeskText, startX + aiW, centerY);
}

function drawPageFooter(
  doc: jsPDF,
  pageW: number,
  pageH: number,
  page: number,
  total: number,
) {
  const fy = pageH - FOOTER_H;

  doc.setFillColor(...NAVY);
  doc.rect(0, fy, pageW, FOOTER_H, 'F');

  doc.setFont('helvetica', 'italic');
  doc.setFontSize(7.5);
  doc.setTextColor(...TEXT_3);
  doc.text(
    'This report is generated by AI HelpDesk and is for guidance only.',
    pageW / 2,
    fy + 11,
    { align: 'center' },
  );

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(...TEXT_2);
  doc.text(`Page ${page} of ${total}`, pageW - MARGIN, fy + 11, {
    align: 'right',
  });
}

function drawNumberBadge(doc: jsPDF, x: number, cy: number, n: number) {
  const r = 3;

  doc.setFillColor(...BLUE);
  doc.circle(x, cy, r, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(n > 9 ? 5 : 6);
  doc.text(String(n), x, cy + (n > 9 ? 1 : 1.2), {
    align: 'center',
  });
}

function drawPill(
  doc: jsPDF,
  x: number,
  y: number,
  w: number,
  h: number,
  fillColor: RGB,
  accentColor: RGB,
) {
  doc.setFillColor(...fillColor);
  doc.roundedRect(x, y, w, h, 2, 2, 'F');

  doc.setFillColor(...accentColor);
  doc.roundedRect(x, y, 2.5, h, 1, 1, 'F');
}

export async function downloadChatReport({
  token,
  chatId,
}: DownloadChatReportOptions): Promise<void> {
  const data = await getChat(token, chatId);

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const bodyW = pageW - MARGIN * 2;
  const bodyBottom = pageH - FOOTER_H - 4;

  const now = new Date();

  const generatedAt = now.toLocaleString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  const questions = Array.isArray(data.chat_questions)
    ? data.chat_questions
    : [];

  drawPageHeader(doc, pageW);

  let y = HEADER_H + 10;

  doc.setTextColor(...BRAND_900);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.text('Assessment Report', MARGIN, y);

  y += 7;
  drawGradientLine(doc, MARGIN, y, 74, 1);
  y += 10;

  const cardX = MARGIN;
  const cardY = y;
  const cardW = bodyW;
  const cardH = 22;

  doc.setFillColor(...BRAND_50);
  doc.roundedRect(cardX, cardY, cardW, cardH, 3, 3, 'F');

  doc.setFillColor(...BLUE);
  doc.roundedRect(cardX, cardY, 3.5, cardH, 1.7, 1.7, 'F');

  const col1X = cardX + 9;
  const row1Y = cardY + 9;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(...TEXT_3);
  doc.text('GENERATED ON', col1X, row1Y);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(...BRAND_900);
  doc.text(generatedAt, col1X, row1Y + 4.5);

  y = cardY + cardH + 14;

  doc.setDrawColor(...DIVIDER);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, y, pageW - MARGIN, y);
  y += 16;

  const PAGE_START_Y = MARGIN;

  function ensureSpace(needed: number) {
    if (y + needed > bodyBottom) {
      doc.addPage();
      y = PAGE_START_Y;
    }
  }

  for (let i = 0; i < questions.length; i++) {
    const q = questions[i];

    doc.setFontSize(10);
    const titleLines = doc.splitTextToSize(
      q.question_title || 'Untitled question',
      bodyW - 12,
    );

    doc.setFontSize(8.5);
    const descLines = q.question_description
      ? doc.splitTextToSize(q.question_description, bodyW - 12)
      : [];

    doc.setFontSize(9.5);
    const answerText = q.selected_answer || 'Not answered';
    const answerLines = doc.splitTextToSize(answerText, bodyW - 18);

    const TLH = 5.5;
    const DLH = 4.5;
    const ALH = 5;

    const titleH = titleLines.length * TLH;
    const descH = descLines.length > 0 ? descLines.length * DLH + 3 : 0;
    const pillH = Math.max(answerLines.length * ALH + 5, 11);
    const blockH = titleH + descH + pillH + 8;

    ensureSpace(blockH);

    drawNumberBadge(doc, MARGIN + 3.5, y + 1.5, i + 1);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(...TEXT_BODY);
    doc.text(titleLines, MARGIN + 10, y + 2.5);
    y += titleH + 2;

    if (descLines.length > 0) {
      ensureSpace(descH);

      doc.setFont('helvetica', 'italic');
      doc.setFontSize(8.5);
      doc.setTextColor(...TEXT_MID);
      doc.text(descLines, MARGIN + 10, y);
      y += descH;
    }

    ensureSpace(pillH + 4);

    if (q.selected_answer) {
      drawPill(doc, MARGIN + 10, y, bodyW - 10, pillH, ANSWER_BG, MINT);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(...TEXT_3);
      doc.text('ANSWER', MARGIN + 16, y + 4);

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9.5);
      doc.setTextColor(...ANSWER_FG);
      doc.text(answerLines, MARGIN + 16, y + 9);
    } else {
      drawPill(doc, MARGIN + 10, y, bodyW - 10, pillH, SKIP_BG, BLUE);

      doc.setFont('helvetica', 'italic');
      doc.setFontSize(9);
      doc.setTextColor(...SKIP_FG);
      doc.text('Not answered', MARGIN + 16, y + 7);
    }

    y += pillH + 8;
  }

  const totalPages: number = (
    doc.internal as unknown as { getNumberOfPages(): number }
  ).getNumberOfPages();

  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    drawPageFooter(doc, pageW, pageH, p, totalPages);
  }

  const filename = `helpdesk-report-${chatId}-${now.toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);
}